window.projectCatalog = {
  categories: [
    {
      id: "causal-inference-experimentation",
      title: "Causal Inference & Experimentation",
      description:
        "Projects in this section focus on estimating effects, designing experiments, and translating evidence into decision-ready recommendations.",
      order: 1,
    },
    {
      id: "time-series-statistical-modelling",
      title: "Time Series & Statistical Modelling",
      description:
        "These projects emphasize forecasting, probabilistic reasoning, and structured statistical modelling on real-world data.",
      order: 2,
    },
    {
      id: "machine-learning-deep-learning",
      title: "Machine Learning & Deep Learning",
      description:
        "This section highlights predictive modelling, representation learning, and model-based decision support across applied domains.",
      order: 3,
    },
    {
      id: "nlp-large-language-model",
      title: "NLP & Large Language Model",
      description:
        "These projects explore language understanding, retrieval, generation, and LLM-based reasoning systems.",
      order: 4,
    },
    {
      id: "data-systems-infrastructure",
      title: "Data Systems & Infrastructure",
      description:
        "Projects here focus on the systems and infrastructure required to make data products reliable, scalable, and usable.",
      order: 5,
    },
  ],
  projects: [
    {
      slug: "minimum-wage-unemployment",
      title: "Minimum Wage Shocks on Unemployment",
      subtitle: "Working Paper · Policy Evaluation",
      topic: "Labor Economics",
      primaryCategory: "Causal Inference & Experimentation",
      displayCategories: ["Causal Inference & Experimentation"],
      tags: ["DiD", "TWFE", "Labor", "Policy", "Panel Data"],
      status: "Working Paper",
      yearLabel: "2025",
      coverLabel: "Policy Shock",
      miniDescription:
        "Studies how minimum wage shocks affect unemployment using panel data methods, difference-in-differences, and two-way fixed effects.",
      resources: [
        {
          label: "Paper",
          href: "./project-resources/minimum-wage-unemployment/paper.pdf",
        },
      ],
      sourcePaths: ["/Users/ricky/Desktop/找工/文书/作品集/Minimum_Wage_Working_Paper.pdf"],
      sourceTypes: ["pdf"],
      detailType: "research-paper",
      sections: {
        problemDefinition: true,
        whyItMatters: true,
        dataAndSetup: true,
        methodDesign: true,
        modelPath: true,
        systemPipeline: false,
        mathematicalCore: true,
        evaluation: true,
        decisionTakeaway: true,
        limitations: true,
        nextSteps: true,
      },
    },
    {
      slug: "nutrition-label-diet-choices",
      title: "Nutrition Label Education and Healthy Diet Choices",
      subtitle: "Research Paper · Behavioral / Health Economics",
      topic: "Consumer Decision-Making",
      primaryCategory: "Causal Inference & Experimentation",
      displayCategories: ["Causal Inference & Experimentation"],
      tags: ["Experiment Design", "DiD", "Survey", "Health", "Consumer Behavior"],
      status: "Completed",
      yearLabel: "2022",
      coverLabel: "Nutrition Choice",
      miniDescription:
        "Examines whether nutrition label education shifts consumer diet choices through a survey-based experiment and causal treatment-effect estimation.",
      resources: [
        {
          label: "Paper",
          href: "./project-resources/nutrition-label-diet-choices/paper.pdf",
        },
      ],
      sourcePaths: [
        "/Users/ricky/Desktop/找工/文书/作品集/Nutrition Label Education on Healthy Diet Choices (Reduced File Size).pdf",
      ],
      sourceTypes: ["pdf"],
      detailType: "research-paper",
      sections: {
        problemDefinition: true,
        whyItMatters: true,
        dataAndSetup: true,
        methodDesign: true,
        modelPath: true,
        systemPipeline: false,
        mathematicalCore: true,
        evaluation: true,
        decisionTakeaway: true,
        limitations: true,
        nextSteps: true,
      },
    },
    {
      slug: "email-funding-conversion-experiment",
      title: "Email Delivery Experiment on Funding Conversion",
      subtitle: "Fintech Product Experimentation",
      topic: "Experimentation",
      primaryCategory: "Causal Inference & Experimentation",
      displayCategories: ["Causal Inference & Experimentation"],
      tags: ["A/B Testing", "Experimentation", "Fintech", "Funnel Analysis", "Product Analytics"],
      status: "Completed",
      yearLabel: "2026",
      coverLabel: "Fintech Experiment",
      miniDescription:
        "Designs and analyzes a multi-arm email experiment to understand funding conversion behavior using experimentation, funnel analytics, and product metrics.",
      resources: [
        {
          label: "Report",
          href: "./project-resources/email-funding-conversion-experiment/report.pdf",
        },
      ],
      sourcePaths: ["/Users/ricky/Desktop/找工/Data班课/Project-3"],
      sourceTypes: ["readme", "notebook", "report", "assets"],
      detailType: "applied-ml",
      sections: {
        problemDefinition: true,
        whyItMatters: true,
        dataAndSetup: true,
        methodDesign: true,
        modelPath: false,
        systemPipeline: false,
        mathematicalCore: false,
        evaluation: true,
        decisionTakeaway: true,
        limitations: true,
        nextSteps: true,
      },
    },
    {
      slug: "bgm-focused-task-performance",
      title: "The Effect of Background Music on Focused Tasks",
      subtitle: "Working Paper · Experimental Design",
      topic: "Behavioral Experiment",
      primaryCategory: "Causal Inference & Experimentation",
      displayCategories: ["Causal Inference & Experimentation", "Time Series & Statistical Modelling"],
      tags: ["Experimental Design", "Mixed Effects", "ANOVA", "Behavior", "Statistics"],
      status: "Working Paper",
      yearLabel: "2024",
      coverLabel: "Behavior Study",
      miniDescription:
        "Tests how background music conditions affect focused-task performance using controlled experimental design and statistical modelling.",
      resources: [
        {
          label: "Paper",
          href: "./project-resources/bgm-focused-task-performance/paper.pdf",
        },
      ],
      sourcePaths: ["/Users/ricky/Desktop/找工/文书/作品集/BGM_Working_Paper.pdf"],
      sourceTypes: ["pdf"],
      detailType: "research-paper",
      sections: {
        problemDefinition: true,
        whyItMatters: true,
        dataAndSetup: true,
        methodDesign: true,
        modelPath: true,
        systemPipeline: false,
        mathematicalCore: true,
        evaluation: true,
        decisionTakeaway: true,
        limitations: true,
        nextSteps: true,
      },
    },
    {
      slug: "natural-gas-consumption-forecasting",
      title: "U.S. Natural Gas Consumption Forecasting",
      subtitle: "STAT 429 · Time Series Analysis",
      topic: "Forecasting",
      primaryCategory: "Time Series & Statistical Modelling",
      displayCategories: ["Time Series & Statistical Modelling"],
      tags: ["Time Series", "Forecasting", "R", "Energy", "Statistical Modelling"],
      status: "Completed",
      yearLabel: "2024",
      coverLabel: "Energy Forecast",
      miniDescription:
        "Forecasts U.S. natural gas consumption using time series analysis and structured statistical modelling on energy and macroeconomic data.",
      resources: [
        {
          label: "Report",
          href: "./project-resources/natural-gas-consumption-forecasting/report.pdf",
        },
      ],
      sourcePaths: ["/Users/ricky/Desktop/UIUC/STAT429/Project"],
      sourceTypes: ["rmd", "pdf", "html", "xlsx"],
      detailType: "research-paper",
      sections: {
        problemDefinition: true,
        whyItMatters: true,
        dataAndSetup: true,
        methodDesign: true,
        modelPath: true,
        systemPipeline: false,
        mathematicalCore: true,
        evaluation: true,
        decisionTakeaway: true,
        limitations: true,
        nextSteps: true,
      },
    },
    {
      slug: "bayesian-statistical-modeling",
      title: "Bayesian Statistical Modeling for Final Project",
      subtitle: "STAT 431 · Bayesian Analysis",
      topic: "Bayesian Modelling",
      primaryCategory: "Time Series & Statistical Modelling",
      displayCategories: ["Time Series & Statistical Modelling"],
      tags: ["Bayesian", "MCMC", "Posterior Inference", "R", "Statistical Modelling"],
      status: "Completed",
      yearLabel: "2024",
      coverLabel: "Bayesian Posterior",
      miniDescription:
        "Uses Bayesian modelling and posterior inference to study a structured statistical question with probabilistic reasoning and computation.",
      resources: [
        {
          label: "Report",
          href: "./project-resources/bayesian-statistical-modeling/report.pdf",
        },
      ],
      sourcePaths: ["/Users/ricky/Desktop/UIUC/STAT431/Project"],
      sourceTypes: ["rmd", "pdf", "html"],
      detailType: "research-paper",
      sections: {
        problemDefinition: true,
        whyItMatters: true,
        dataAndSetup: true,
        methodDesign: true,
        modelPath: true,
        systemPipeline: false,
        mathematicalCore: true,
        evaluation: true,
        decisionTakeaway: true,
        limitations: true,
        nextSteps: true,
      },
    },
    {
      slug: "champaign-rental-price-forecasting",
      title: "Forecasting Rental Prices in Champaign",
      subtitle: "URES Fellow Project · Housing Forecasting",
      topic: "Housing Analytics",
      primaryCategory: "Time Series & Statistical Modelling",
      displayCategories: ["Time Series & Statistical Modelling", "Machine Learning & Deep Learning"],
      tags: ["Time Series", "Forecasting", "Housing", "DuckDB", "LSTM"],
      status: "Completed",
      yearLabel: "2024",
      coverLabel: "Housing Forecast",
      miniDescription:
        "Forecasts rental prices in Champaign using time series methods and machine learning models on housing, demographic, and macroeconomic signals.",
      resources: [
        {
          label: "Paper",
          href: "./project-resources/champaign-rental-price-forecasting/paper.pdf",
        },
      ],
      sourcePaths: ["/Users/ricky/Desktop/找工/文书/作品集/URES_Paper.pdf"],
      sourceTypes: ["pdf"],
      detailType: "research-paper",
      sections: {
        problemDefinition: true,
        whyItMatters: true,
        dataAndSetup: true,
        methodDesign: true,
        modelPath: true,
        systemPipeline: true,
        mathematicalCore: true,
        evaluation: true,
        decisionTakeaway: true,
        limitations: true,
        nextSteps: true,
      },
    },
    {
      slug: "amazon-food-review-sentiment-analysis",
      title: "Amazon Food Review Sentiment Analysis",
      subtitle: "Applied NLP Classification Project",
      topic: "Customer Feedback Analytics",
      primaryCategory: "Machine Learning & Deep Learning",
      displayCategories: ["Machine Learning & Deep Learning", "NLP & Large Language Model"],
      tags: ["Sentiment Analysis", "TF-IDF", "Word2Vec", "Classification", "NLP"],
      status: "Completed",
      yearLabel: "2026",
      coverLabel: "Review Signals",
      miniDescription:
        "Builds a sentiment classification workflow for customer reviews using feature engineering, NLP representations, and supervised learning.",
      resources: [
        {
          label: "Paper",
          href: "./project-resources/amazon-food-review-sentiment-analysis/paper.pdf",
        },
      ],
      sourcePaths: ["/Users/ricky/Desktop/找工/Data班课/Project-1"],
      sourceTypes: ["readme", "notebook", "paper", "models"],
      detailType: "applied-ml",
      sections: {
        problemDefinition: true,
        whyItMatters: true,
        dataAndSetup: true,
        methodDesign: false,
        modelPath: true,
        systemPipeline: true,
        mathematicalCore: false,
        evaluation: true,
        decisionTakeaway: true,
        limitations: true,
        nextSteps: true,
      },
    },
    {
      slug: "conversion-rate-modeling-optimization",
      title: "Conversion Rate Modeling and Optimization",
      subtitle: "Applied Predictive Modeling Project",
      topic: "Business Conversion Analytics",
      primaryCategory: "Machine Learning & Deep Learning",
      displayCategories: ["Machine Learning & Deep Learning"],
      tags: ["Classification", "XGBoost", "LightGBM", "Threshold Tuning", "Business Analytics"],
      status: "Completed",
      yearLabel: "2026",
      coverLabel: "Conversion Funnel",
      miniDescription:
        "Models conversion probability and business optimization tradeoffs using supervised learning, threshold tuning, and conversion analytics.",
      resources: [],
      sourcePaths: ["/Users/ricky/Desktop/找工/Data班课/Project-2"],
      sourceTypes: ["notebook", "pkl", "csv", "docx"],
      detailType: "applied-ml",
      sections: {
        problemDefinition: true,
        whyItMatters: true,
        dataAndSetup: true,
        methodDesign: false,
        modelPath: true,
        systemPipeline: true,
        mathematicalCore: false,
        evaluation: true,
        decisionTakeaway: true,
        limitations: true,
        nextSteps: true,
      },
    },
    {
      slug: "trm-mechanistic-interpretability",
      title: "Mechanistic Interpretability for TRM",
      subtitle: "ESE 5460 Project",
      topic: "Model Interpretability",
      primaryCategory: "Machine Learning & Deep Learning",
      displayCategories: ["Machine Learning & Deep Learning", "NLP & Large Language Model"],
      tags: ["Interpretability", "SAE", "Ablation", "PyTorch", "Deep Learning"],
      status: "Completed",
      yearLabel: "2026",
      coverLabel: "Model Circuits",
      miniDescription:
        "Studies mechanistic interpretability through sparse autoencoders, ablation workflows, and model-behavior analysis in deep learning systems.",
      resources: [
        {
          label: "Report",
          href: "./project-resources/trm-mechanistic-interpretability/report.pdf",
        },
      ],
      sourcePaths: ["/Users/ricky/Desktop/Penn/ESE5460/Project"],
      sourceTypes: ["pdf", "ipynb", "readme", "py"],
      detailType: "applied-ml",
      sections: {
        problemDefinition: true,
        whyItMatters: true,
        dataAndSetup: true,
        methodDesign: true,
        modelPath: true,
        systemPipeline: true,
        mathematicalCore: true,
        evaluation: true,
        decisionTakeaway: true,
        limitations: true,
        nextSteps: true,
      },
    },
    {
      slug: "llm-powered-churn-analysis-system",
      title: "LLM-Powered Churn Analysis System",
      subtitle: "Industry Project · Eth Tech",
      topic: "Customer Retention Intelligence",
      primaryCategory: "NLP & Large Language Model",
      displayCategories: ["NLP & Large Language Model", "Machine Learning & Deep Learning"],
      tags: ["LLM", "RAG", "Fine-Tuning", "Churn", "Predictive Modelling"],
      status: "Completed",
      yearLabel: "2025",
      coverLabel: "Retention Copilot",
      miniDescription:
        "Builds an LLM-powered churn analysis workflow using retrieval, fine-tuning, and structured feedback processing for decision support.",
      resources: [
        {
          label: "GitHub",
          href: "https://github.com/Ricky-S-Gong/LLM-Churn-Analysis-System",
        },
        {
          label: "Paper",
          href: "./project-resources/llm-powered-churn-analysis-system/paper.pdf",
        },
      ],
      sourcePaths: ["/Users/ricky/Desktop/LLM-Project"],
      sourceTypes: ["readme", "paper", "ipynb", "py", "data"],
      detailType: "llm-system",
      sections: {
        problemDefinition: true,
        whyItMatters: true,
        dataAndSetup: true,
        methodDesign: true,
        modelPath: true,
        systemPipeline: true,
        mathematicalCore: false,
        evaluation: true,
        decisionTakeaway: true,
        limitations: true,
        nextSteps: true,
      },
    },
    {
      slug: "tool-using-language-models",
      title: "Tool-Using Language Models",
      subtitle: "CIS 6200 Project",
      topic: "LLM Reasoning & Tool Use",
      primaryCategory: "NLP & Large Language Model",
      displayCategories: ["NLP & Large Language Model"],
      tags: ["LLM", "Tool Use", "Agents", "Reasoning", "Evaluation"],
      status: "In Progress",
      yearLabel: "2026",
      coverLabel: "Tool Use",
      miniDescription:
        "Explores how language models invoke external tools and structured actions to improve reasoning and task completion.",
      resources: [
        {
          label: "PDF",
          href: "./project-resources/tool-using-language-models/pdf.pdf",
        },
      ],
      sourcePaths: ["/Users/ricky/Desktop/CIS6200/Project"],
      sourceTypes: ["proposal", "md"],
      detailType: "in-progress-llm",
      sections: {
        problemDefinition: true,
        whyItMatters: true,
        dataAndSetup: false,
        methodDesign: true,
        modelPath: true,
        systemPipeline: true,
        mathematicalCore: false,
        evaluation: true,
        decisionTakeaway: false,
        limitations: false,
        nextSteps: true,
      },
    },
    {
      slug: "trustworthy-rl-llm-reasoning",
      title: "Trustworthy RL with LLM-Based Reasoning",
      subtitle: "CIS 5270 Project",
      topic: "Trustworthy AI",
      primaryCategory: "NLP & Large Language Model",
      displayCategories: ["NLP & Large Language Model", "Machine Learning & Deep Learning"],
      tags: ["RL", "LLM", "Trustworthy AI", "Safety", "Evaluation"],
      status: "In Progress",
      yearLabel: "2026",
      coverLabel: "Trustworthy Agent",
      miniDescription:
        "Investigates trustworthy reinforcement learning with LLM-based reasoning, evaluation, and safety-oriented design constraints.",
      resources: [
        {
          label: "PDF",
          href: "./project-resources/trustworthy-rl-llm-reasoning/pdf.pdf",
        },
      ],
      sourcePaths: ["/Users/ricky/Desktop/CIS5270/Project"],
      sourceTypes: ["proposal", "md"],
      detailType: "in-progress-llm",
      sections: {
        problemDefinition: true,
        whyItMatters: true,
        dataAndSetup: false,
        methodDesign: true,
        modelPath: true,
        systemPipeline: true,
        mathematicalCore: false,
        evaluation: true,
        decisionTakeaway: false,
        limitations: false,
        nextSteps: true,
      },
    },
    {
      slug: "pennos",
      title: "PennOS",
      subtitle: "Operating Systems Project",
      topic: "Systems Programming",
      primaryCategory: "Data Systems & Infrastructure",
      displayCategories: ["Data Systems & Infrastructure"],
      tags: ["Operating Systems", "C", "Shell", "Scheduling", "Systems"],
      status: "Completed",
      yearLabel: "2025",
      coverLabel: "OS Runtime",
      miniDescription:
        "Builds an operating-system-style environment with shell, scheduling, and systems programming components in C.",
      resources: [
        {
          label: "Report",
          href: "./project-resources/pennos/report.pdf",
        },
      ],
      sourcePaths: ["/Users/ricky/Desktop/Penn/CIS5480/jammy/25fa-cis5480-pennos-34"],
      sourceTypes: ["readme", "pdf", "c", "makefile"],
      detailType: "systems-project",
      sections: {
        problemDefinition: true,
        whyItMatters: true,
        dataAndSetup: false,
        methodDesign: false,
        modelPath: false,
        systemPipeline: true,
        mathematicalCore: false,
        evaluation: true,
        decisionTakeaway: true,
        limitations: true,
        nextSteps: true,
      },
    },
    {
      slug: "penncloud",
      title: "PennCloud",
      subtitle: "Distributed Systems Project",
      topic: "Distributed Infrastructure",
      primaryCategory: "Data Systems & Infrastructure",
      displayCategories: ["Data Systems & Infrastructure"],
      tags: ["Distributed Systems", "C++", "KV Store", "Replication", "Backend"],
      status: "In Progress",
      yearLabel: "2026",
      coverLabel: "Distributed Store",
      miniDescription:
        "Implements a distributed cloud-style system with backend coordination, storage, and service interfaces across multiple components.",
      resources: [
        {
          label: "Report",
          href: "./project-resources/penncloud/report.pdf",
        },
      ],
      sourcePaths: ["/Users/ricky/Desktop/CIS5050/26sp-CIS5050-Ricky-S-Gong/sp26-cis5050-T04"],
      sourceTypes: ["readme", "md", "pdf", "cc", "h", "py"],
      detailType: "systems-project",
      sections: {
        problemDefinition: true,
        whyItMatters: true,
        dataAndSetup: false,
        methodDesign: false,
        modelPath: false,
        systemPipeline: true,
        mathematicalCore: false,
        evaluation: true,
        decisionTakeaway: true,
        limitations: true,
        nextSteps: true,
      },
    },
  ],
};
